### ISSUE TITLE
Questions for Go devs

### ISSUE THREAD

**Issue by ezzatron** [ezzatron/nvector-go#3]
- Feels weird to duplicate default options in the internal options package.
- Ellipsoid in options or no?
- Functions that accept depths - provide variants for 0-depth? Or just always specify?
- r3.Vec uses values, r3.Mat uses pointers. When should I? Ellipsoids?
- General naming audit.
- Test assertion helpers?
- Docs preview?

**Comment by jmalloc** [comment]
# Feels weird to duplicate default options in the internal options package.

You could move the canonical definition into the internal `options` package, and expose it at the root level the same way we do with the type alias of `Option` itself.

# Functions that accept depths - provide variants for 0-depth? Or just always specify?

If they're unexpected I'd just always specify it. Got an example of such a function that's part of the public API?

# Ellipsoid in options or no?

It probably depends on typical usage, which I'm not sure we know. Danil suggested having the operations be methods on some struct that holds this kind of "global space" configuration, which might be worth exploring.

# Test assertion helpers?

- https://github.com/stretchr/testify - The closest thing to a defect standard, but I don't use it
- https://github.com/shoenig/test - I wan't to take a look at this

The Go team advocates _against_ helpers, which personally I'm still not really on-board with, but I have been trying to avoid them to get a feel for what it's really like with NO helpers, but I don't think I've tested anything remotely complex without at least reaching for https://github.com/google/go-cmp

# r3.Vec uses values, r3.Mat uses pointers. When should I? Ellipsoids?

The best rule of thumb I can give is to use pointer receivers when the type you're writing should have "entity semantics", i.e. two "instances", even with equivalent values, are not considered the same. Avoid pointer receives when you want "value semantics". There's a million reasons to violate this ideal, but it does seem kind of surprising to me that a matrix would NOT be treated as a value.

# Docs preview?

Run a local instance of `pkg.go.dev` on https://localhost:8080 with:

```bash
go install golang.org/x/pkgsite/cmd/pkgsite@latest
pkgsite
```

**Comment by ezzatron** [comment]
Appreciate the replies. These were more notes for a verbal discussion, and incomplete at that. Maybe Friday?

**Comment by jmalloc** [comment]
Cool, no worries.
